### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by F4GXS**
2 new screen + 1 update (Samsung SyncMaster Area)

### CODE REVIEW

**Comment by simolg** [comment]
. . . this project is rarely updated . . . I think
in the meantime I added your report here: https://15khz.miraheze.org

**Comment by F4GXS** [comment]
> . . . this project is rarely updated . . . I think in the meantime I added your report here: https://15khz.miraheze.org

Yes, no problem !
It's possible to send update directly to you ?
I would like to avoid going through pull requests.

**Comment by F4GXS** [comment]
SyncMaster 913N and SyncMaster 172V are working only in Black&White directly thru VGA with Atari 1040STE, color not available due to Horizontal Frequency

**Comment by simolg** [comment]
both monitors work in black and white?
I can't validate pull requests on GitHub :/
for this problem I started the page on miraheze, there the modification is free and immediate, just click on "edit"

**Comment by F4GXS** [comment]
> both monitors work in black and white? I can't validate pull requests on GitHub :/ for this problem I started the page on miraheze, there the modification is free and immediate, just click on "edit"

Yes, both monitors screen are working only in B&W, i make a video cable DIN 13 Pins to VGA for Monochrome
I'm going to "Miraheze" to make modifications.
Thanks !

### PULL REQUEST CLOSED ###

**Comment by planeturban** [comment]
Yeah, life and stuff. Been meaning to move this to the 15khz org at github.

**Pull request merged**
